#spring.profiles.active=sqlserver
spring.profiles.active=mysql
spring.config.import=optional:application-local-${spring.profiles.active}.properties
jwt.secret=my-super-secret-key-12345678901234567890
jwt.expiration=86400000